@startuml
!include style.puml
skinparam ArrowFontStyle plain
!define input "/add_team module/CS2103T tutorial/T09 name/Team 1 size/5"


box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant ":AddTeamCommandParser" as AddTeamCommandParser LOGIC_COLOR
participant "d:AddTeamCommand" as AddTeamCommand LOGIC_COLOR
participant "r:CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant "m:Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute(input)
activate LogicManager

LogicManager -> AddressBookParser : parseCommand(input)
activate AddressBookParser

create AddTeamCommandParser
AddressBookParser -> AddTeamCommandParser
activate AddTeamCommandParser

AddTeamCommandParser --> AddressBookParser
deactivate AddTeamCommandParser

AddressBookParser -> AddTeamCommandParser : parse("module/CS2103T tutorial/T09 name/Team 1 size/5")
activate AddTeamCommandParser

create AddTeamCommand
AddTeamCommandParser -> AddTeamCommand
activate AddTeamCommand

AddTeamCommand --> AddTeamCommandParser
deactivate AddTeamCommand

AddTeamCommandParser --> AddressBookParser : d(p)
deactivate AddTeamCommandParser

AddressBookParser --> LogicManager : d(p)
deactivate AddressBookParser

LogicManager -> AddTeamCommand : execute(m)
activate AddTeamCommand

AddTeamCommand -> Model : addTeam(p)
activate Model

Model --> AddTeamCommand
deactivate Model

create CommandResult
AddTeamCommand -> CommandResult
activate CommandResult

CommandResult --> AddTeamCommand
deactivate CommandResult

AddTeamCommand --> LogicManager : r
deactivate AddTeamCommand

[<--LogicManager
deactivate LogicManager

@enduml
