@startuml
!include style.puml
skinparam ArrowFontStyle plain
!define input "/delete_student id/A0123456X"


box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant ":DeleteStudentCommandParser" as DeleteStudentCommandParser LOGIC_COLOR
participant "d:DeleteByIdStudentCommand" as DeleteStudentByIdCommand LOGIC_COLOR
participant "r:CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant "m:Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute(input)
activate LogicManager

LogicManager -> AddressBookParser : parseCommand(input)
activate AddressBookParser

create DeleteStudentCommandParser
AddressBookParser -> DeleteStudentCommandParser
activate DeleteStudentCommandParser

DeleteStudentCommandParser --> AddressBookParser
deactivate DeleteStudentCommandParser

AddressBookParser -> DeleteStudentCommandParser : parse("id/A0123456X")
activate DeleteStudentCommandParser

create DeleteStudentByIdCommand
DeleteStudentCommandParser -> DeleteStudentByIdCommand
activate DeleteStudentByIdCommand

DeleteStudentByIdCommand --> DeleteStudentCommandParser :
deactivate DeleteStudentByIdCommand

DeleteStudentCommandParser --> AddressBookParser : d
deactivate DeleteStudentCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
DeleteStudentCommandParser -[hidden]-> AddressBookParser
destroy DeleteStudentCommandParser

AddressBookParser --> LogicManager : d
deactivate AddressBookParser

LogicManager -> DeleteStudentByIdCommand : execute(m)
activate DeleteStudentByIdCommand

DeleteStudentByIdCommand -> Model : searchPersonByPredicate()
activate Model

Model --> DeleteStudentByIdCommand : p
deactivate Model

DeleteStudentByIdCommand -> Model : deletePerson(p)
activate Model

Model --> DeleteStudentByIdCommand
deactivate Model

create CommandResult
DeleteStudentByIdCommand -> CommandResult
activate CommandResult

CommandResult --> DeleteStudentByIdCommand
deactivate CommandResult

DeleteStudentByIdCommand --> LogicManager : r
deactivate DeleteStudentByIdCommand

[<--LogicManager
deactivate LogicManager
@enduml
